package handlers

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/JpUnique/petrodata-leave-project/pkg/database"
	"github.com/JpUnique/petrodata-leave-project/pkg/models"
	"golang.org/x/crypto/bcrypt"
)

// Signup handles the registration of new staff members.
func Signup(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	defer r.Body.Close()

	var user models.User
	if err := json.NewDecoder(r.Body).Decode(&user); err != nil {
		http.Error(w, "bad request: invalid JSON", http.StatusBadRequest)
		return
	}

	// 1. Check if user already exists
	var existingUser models.User
	err := database.DB.Where("email = ?", user.Email).First(&existingUser).Error
	if err == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusConflict)
		json.NewEncoder(w).Encode(map[string]string{"error": "User with this email already exists"})
		return
	}

	// 2. Hash the password before saving (Security update)
	// bcrypt.DefaultCost is a good balance between security and speed
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(user.Password), bcrypt.DefaultCost)
	if err != nil {
		http.Error(w, "failed to hash password", http.StatusInternalServerError)
		return
	}
	user.Password = string(hashedPassword) // Replace the plain text password with the hash

	// 3. Set defaults
	user.CreatedAt = time.Now()

	// 4. Database insertion
	// Since we used SERIAL in Postgres, we don't pass an ID; Postgres generates it.
	if err := database.DB.Create(&user).Error; err != nil {
		http.Error(w, "failed to create user in database", http.StatusInternalServerError)
		return
	}

	// 5. Success Response
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message": "Registration successful for " + user.FullName,
		"user_id": user.ID, // GORM automatically populates this from the Postgres SERIAL ID
		"email":   user.Email,
	})
}

// SubmitLeaveRequest handles the submission of the leave form.
// SubmitLeaveRequest handles the submission of the leave form to PostgreSQL.
func SubmitLeaveRequest(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var leaveReq models.LeaveRequest
	if err := json.NewDecoder(r.Body).Decode(&leaveReq); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]string{"error": "Invalid JSON data"})
		return
	}

	// 1. Set default values for a new request
	leaveReq.CreatedAt = time.Now()
	leaveReq.Status = "Pending"

	// Explicitly set approval booleans to false for the new record
	leaveReq.ManagerApproved = false
	leaveReq.HRApproved = false
	leaveReq.MDApproved = false

	// 2. Save to PostgreSQL via GORM
	// Postgres SERIAL will automatically generate the ID
	if err := database.DB.Create(&leaveReq).Error; err != nil {
		http.Error(w, "Database error: Could not save leave request", http.StatusInternalServerError)
		return
	}

	// 3. Return success response with the new ID
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusAccepted)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"message":    "Leave request submitted successfully for " + leaveReq.StaffName,
		"request_id": leaveReq.ID, // This is the ID generated by Postgres SERIAL
		"status":     leaveReq.Status,
	})
}

// Login verifies user credentials against the database.
func Login(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	defer r.Body.Close()

	// 1. Create a temporary struct to capture login input
	var input struct {
		Email    string `json:"email"`
		Password string `json:"password"`
	}

	if err := json.NewDecoder(r.Body).Decode(&input); err != nil {
		http.Error(w, "invalid JSON", http.StatusBadRequest)
		return
	}

	// 2. Query the database for the user by Email ONLY
	var user models.User
	err := database.DB.Where("email = ?", input.Email).First(&user).Error
	if err != nil {
		http.Error(w, "invalid email or password", http.StatusUnauthorized)
		return
	}

	// 3. Compare the hashed password from DB with the plain password from user
	err = bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password))
	if err != nil {
		// This means the password was wrong
		http.Error(w, "invalid email or password", http.StatusUnauthorized)
		return
	}

	// 3. Return success response
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{
		"message": "Login successful",
		"user":    user.FullName,
	})
}
